sudo: required

branches:
  only:
  - master
  - index-page
  - /201[7-9][0-1][0-9][0-3][0-9]/

cache: yarn

language: node_js

addons:
  firefox: "47.0"

before_install:
- export TZ=Europe/Helsinki

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install: true

services:
  - docker

jobs:
  include:

    - stage: flow
      env: FLOW=1
      node_js: "8"
      script: test/flow.sh

    - stage: visual
      env: VISUAL=chrome
      node_js: "8"
      script: test/visual.sh
    - stage: visual
      env: VISUAL=ie11
      node_js: "8"
      script: test/visual.sh
    - stage: visual
      env: VISUAL=edge15
      node_js: "8"
      script: test/visual.sh
    - stage: visual
      env: VISUAL=safari10
      node_js: "8"
      script: test/visual.sh
    - stage: visual
      env: VISUAL=firefox
      node_js: "8"
      script: test/visual.sh

    - stage: build and deploy container
      node_js: "8"
      script: test/deploy.sh
