sudo: required

branches:
  only:
  - master
  - index-page
  - /201[7-9][0-1][0-9][0-3][0-9]/

cache: yarn

language: node_js

install:
  - test/install.sh

services:
  - docker

jobs:
  include:
    - stage: test
      env: VISUAL=chrome
      node_js: "8"
      script: test/visual.sh
    - stage: build container and deploy
      node_js: "8"
      script: test/deploy.sh
